# Generated by Django 5.1.6 on 2025-05-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_code", models.CharField(max_length=32, unique=True)),
                ("sender", models.CharField(max_length=128)),
                ("receiver", models.CharField(max_length=128)),
                (
                    "receiver_image",
                    models.ImageField(blank=True, null=True, upload_to="shipments/"),
                ),
                ("origin", models.CharField(max_length=128)),
                ("destination", models.CharField(max_length=128)),
                ("weight", models.CharField(max_length=32)),
                ("shipped_on", models.DateField()),
                ("expected_delivery", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("order_placed", "Order Placed"),
                            ("dispatched", "Dispatched"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="order_placed",
                        max_length=20,
                    ),
                ),
                (
                    "shipment_image",
                    models.ImageField(blank=True, null=True, upload_to="shipments/"),
                ),
            ],
        ),
    ]
